/* Generates src/embedded.c from the themes, starters and ui folders.
 * Usage: embed <out.c> <dir> [dir...] */
#define _XOPEN_SOURCE 700
#include <dirent.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

static FILE *out;
static char **paths;
static size_t count, cap;

static void walk(const char *dir) {
    DIR *d = opendir(dir);
    if (!d) { fprintf(stderr, "embed: cannot open %s\n", dir); exit(1); }
    struct dirent *e;
    char **names = NULL;
    size_t n = 0;
    while ((e = readdir(d))) {
        if (e->d_name[0] == '.' && strcmp(e->d_name, ".htaccess") != 0) continue;
        names = realloc(names, sizeof(char *) * (n + 1));
        names[n++] = strdup(e->d_name);
    }
    closedir(d);
    for (size_t i = 0; i + 1 < n; i++)
        for (size_t j = i + 1; j < n; j++)
            if (strcmp(names[i], names[j]) > 0) { char *t = names[i]; names[i] = names[j]; names[j] = t; }
    for (size_t i = 0; i < n; i++) {
        char p[4096];
        snprintf(p, sizeof p, "%s/%s", dir, names[i]);
        struct stat st;
        if (stat(p, &st) != 0) continue;
        if (S_ISDIR(st.st_mode)) walk(p);
        else if (S_ISREG(st.st_mode)) {
            if (count == cap) { cap = cap ? cap * 2 : 64; paths = realloc(paths, sizeof(char *) * cap); }
            paths[count++] = strdup(p);
        }
        free(names[i]);
    }
    free(names);
}

int main(int argc, char **argv) {
    if (argc < 3) { fprintf(stderr, "usage: embed out.c dir...\n"); return 1; }
    for (int i = 2; i < argc; i++) walk(argv[i]);
    out = fopen(argv[1], "w");
    if (!out) { perror(argv[1]); return 1; }
    fputs("/* Generated by tools/embed.c. Do not edit. */\n#include \"embedded.h\"\n\n", out);
    for (size_t i = 0; i < count; i++) {
        FILE *f = fopen(paths[i], "rb");
        if (!f) { perror(paths[i]); return 1; }
        fprintf(out, "static const unsigned char f%zu[] = {", i);
        int c, col = 0;
        size_t len = 0;
        while ((c = fgetc(f)) != EOF) {
            fprintf(out, "%u,", (unsigned)c);
            len++;
            if (++col == 24) { fputc('\n', out); col = 0; }
        }
        fclose(f);
        if (!len) fputs("0", out);
        fprintf(out, "};\n#define f%zu_len %zuu\n", i, len);
    }
    fputs("\nconst tt_file tt_files[] = {\n", out);
    for (size_t i = 0; i < count; i++) fprintf(out, "    {\"%s\", f%zu, f%zu_len},\n", paths[i], i, i);
    fprintf(out, "    {0, 0, 0}\n};\nconst size_t tt_nfiles = %zuu;\n", count);
    fclose(out);
    fprintf(stderr, "embedded %zu files\n", count);
    return 0;
}
