/* tantu embedded: themes, starter sites and the dashboard are compiled into
 * the program, so tantu is a single file with nothing else to install.
 * src/embedded.c is generated by tools/embed.c (run: make). */
#ifndef TT_EMBEDDED_H
#define TT_EMBEDDED_H

#include <stddef.h>
#include <stdio.h>

typedef struct {
    const char *path;
    const unsigned char *data;
    size_t len;
} tt_file;

extern const tt_file tt_files[];
extern const size_t tt_nfiles;

/* Returns the file contents or NULL. */
const unsigned char *embedded_get(const char *path, size_t *len);

/* Writes every file whose path starts with prefix into dst. Returns the
 * number of files written, or -1 on error. */
int extract_prefix(const char *prefix, const char *dst);

int theme_exists(const char *name);
void list_themes(FILE *out);

#endif
